'use client';

import { useState } from 'react';

type Platform = 'endpoint' | 'cloud';

interface PromptComponent {
  id: string;
  label: string;
  description: string;
  platforms: Platform[];
  enabled: boolean;
}

const defaultComponents: PromptComponent[] = [
  // Placeholder components — real ones will be supplied later
  { id: 'base_config', label: 'Base Configuration', description: 'Core agent identity, role, and behavioral constraints', platforms: ['endpoint', 'cloud'], enabled: true },
  { id: 'policy_context', label: 'Policy Context', description: 'Active DLP policies, rules, and classification labels', platforms: ['endpoint', 'cloud'], enabled: false },
  { id: 'channel_rules', label: 'Channel Rules', description: 'Per-channel enforcement rules (email, web, USB, print, clipboard, cloud apps)', platforms: ['endpoint', 'cloud'], enabled: false },
  { id: 'endpoint_actions', label: 'Endpoint Actions', description: 'Block, warn, encrypt, quarantine actions for endpoint agent', platforms: ['endpoint'], enabled: false },
  { id: 'cloud_actions', label: 'Cloud Actions', description: 'Block, notify, quarantine, redirect actions for cloud DLP', platforms: ['cloud'], enabled: false },
  { id: 'classification', label: 'Data Classification', description: 'Sensitivity labels, data types, regex patterns, and EDM fingerprints', platforms: ['endpoint', 'cloud'], enabled: false },
  { id: 'incident_response', label: 'Incident Response', description: 'Incident creation templates, severity mapping, and escalation rules', platforms: ['endpoint', 'cloud'], enabled: false },
  { id: 'user_notifications', label: 'User Notifications', description: 'End-user popup messages, justification prompts, and coaching text', platforms: ['endpoint', 'cloud'], enabled: false },
  { id: 'exceptions', label: 'Exceptions & Allowlists', description: 'Trusted domains, approved applications, exempt user groups', platforms: ['endpoint', 'cloud'], enabled: false },
  { id: 'reporting', label: 'Reporting & Logging', description: 'Log format, detail level, and reporting destination configuration', platforms: ['endpoint', 'cloud'], enabled: false },
];

export default function PromptBuilderClient() {
  const [platform, setPlatform] = useState<Platform>('endpoint');
  const [components, setComponents] = useState(defaultComponents);
  const [previewVisible, setPreviewVisible] = useState(false);
  const [previewTab, setPreviewTab] = useState<'visual' | 'source'>('visual');

  const filteredComponents = components.filter((c) => c.platforms.includes(platform));
  const enabledComponents = filteredComponents.filter((c) => c.enabled);

  function toggleComponent(id: string) {
    setComponents((prev) =>
      prev.map((c) => (c.id === id ? { ...c, enabled: !c.enabled } : c))
    );
  }

  function selectAll() {
    setComponents((prev) =>
      prev.map((c) => (c.platforms.includes(platform) ? { ...c, enabled: true } : c))
    );
  }

  function selectNone() {
    setComponents((prev) =>
      prev.map((c) => (c.id === 'base_config' ? c : { ...c, enabled: false }))
    );
  }

  function generatePromptHtml(): string {
    // Placeholder — will be replaced with real prompt assembly logic
    const sections = enabledComponents.map((c) => {
      return `<!-- ${c.label} -->\n<section data-component="${c.id}">\n  <h2>${c.label}</h2>\n  <p>${c.description}</p>\n  <!-- Component content will be injected here -->\n</section>`;
    });

    return [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head>`,
      `  <meta charset="UTF-8">`,
      `  <title>Fortra ${platform === 'endpoint' ? 'Endpoint' : 'Cloud'} DLP Prompt</title>`,
      `</head>`,
      `<body>`,
      `  <h1>Fortra ${platform === 'endpoint' ? 'Endpoint' : 'Cloud'} DLP Agent Prompt</h1>`,
      `  <p>Generated by Fortrafied Prompt Builder</p>`,
      `  <p>Platform: Fortra ${platform === 'endpoint' ? 'Endpoint DLP' : 'Cloud DLP'}</p>`,
      `  <p>Components: ${enabledComponents.length}</p>`,
      `  <hr>`,
      ...sections,
      `</body>`,
      `</html>`,
    ].join('\n');
  }

  function downloadPrompt() {
    const html = generatePromptHtml();
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fortra-${platform}-dlp-prompt.html`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function copyPrompt() {
    navigator.clipboard.writeText(generatePromptHtml());
  }

  return (
    <>
      <div className="info-box">
        <strong>Prompt Builder:</strong> Select a Fortra DLP platform and choose which prompt components to include. The builder assembles the components into a single HTML prompt ready for use with the DLP agent.
      </div>

      {/* Platform selector */}
      <div className="test-panel">
        <h2>Select Platform</h2>
        <p>Choose the Fortra DLP platform to build a prompt for.</p>
        <div className="flex gap-3 mt-3">
          <button
            className={`btn ${platform === 'endpoint' ? 'btn-primary' : 'btn-outline'}`}
            onClick={() => setPlatform('endpoint')}
          >
            Fortra Endpoint DLP
          </button>
          <button
            className={`btn ${platform === 'cloud' ? 'btn-primary' : 'btn-outline'}`}
            onClick={() => setPlatform('cloud')}
          >
            Fortra Cloud DLP
          </button>
        </div>
      </div>

      {/* Component selector */}
      <div className="test-panel">
        <h2>Prompt Components</h2>
        <p>
          Toggle the components to include in the generated prompt.
          <span className="tag tag-blue" style={{ marginLeft: 8 }}>
            {enabledComponents.length} selected
          </span>
        </p>

        <div className="flex gap-2 mt-2 mb-3">
          <button className="btn btn-sm btn-outline" onClick={selectAll}>Select All</button>
          <button className="btn btn-sm btn-outline" onClick={selectNone}>Deselect All</button>
        </div>

        <div className="card-grid">
          {filteredComponents.map((c) => (
            <div
              key={c.id}
              className={`card${c.enabled ? '' : ' card-disabled'}`}
              style={{ cursor: 'pointer', opacity: c.enabled ? 1 : 0.5 }}
              onClick={() => toggleComponent(c.id)}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
                <h3 style={{ margin: 0, fontSize: '1rem' }}>{c.label}</h3>
                <input
                  type="checkbox"
                  checked={c.enabled}
                  onChange={() => toggleComponent(c.id)}
                  onClick={(e) => e.stopPropagation()}
                  style={{ accentColor: '#4fc3f7', width: 18, height: 18 }}
                />
              </div>
              <p style={{ marginBottom: 8 }}>{c.description}</p>
              <div className="flex gap-2">
                {c.platforms.map((p) => (
                  <span key={p} className={`tag ${p === 'endpoint' ? 'tag-blue' : 'tag-green'}`}>
                    {p === 'endpoint' ? 'Endpoint' : 'Cloud'}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="test-panel">
        <h2>Generate Prompt</h2>
        <p>
          Build the HTML prompt from your selected components for Fortra{' '}
          {platform === 'endpoint' ? 'Endpoint' : 'Cloud'} DLP.
        </p>

        <div className="flex gap-3 mt-3">
          <button className="btn btn-primary" onClick={() => setPreviewVisible(true)}>
            Preview Prompt
          </button>
          <button className="btn btn-success" onClick={downloadPrompt}>
            Download HTML
          </button>
          <button className="btn btn-outline" onClick={copyPrompt}>
            Copy to Clipboard
          </button>
        </div>

        {previewVisible && (
          <div className="mt-3">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
              <h3 style={{ color: '#fff', margin: 0 }}>Preview</h3>
              <button className="btn btn-sm btn-outline" onClick={() => setPreviewVisible(false)}>
                Close
              </button>
            </div>

            <div className="tabs" style={{ marginBottom: 0 }}>
              <button
                className={`tab-btn${previewTab === 'visual' ? ' active' : ''}`}
                onClick={() => setPreviewTab('visual')}
              >
                Visual
              </button>
              <button
                className={`tab-btn${previewTab === 'source' ? ' active' : ''}`}
                onClick={() => setPreviewTab('source')}
              >
                Source
              </button>
            </div>

            {previewTab === 'visual' ? (
              <div style={{ border: '1px solid #1e2a45', borderRadius: '0 0 8px 8px', overflow: 'hidden' }}>
                <iframe
                  srcDoc={generatePromptHtml()}
                  title="Prompt Preview"
                  sandbox=""
                  style={{
                    width: '100%',
                    height: 500,
                    border: 'none',
                    background: '#fff',
                  }}
                />
              </div>
            ) : (
              <div
                className="code-block"
                style={{ maxHeight: 500, overflowY: 'auto', whiteSpace: 'pre-wrap', fontSize: '0.8rem', borderRadius: '0 0 8px 8px' }}
              >
                {generatePromptHtml()}
              </div>
            )}
          </div>
        )}
      </div>

      <div className="warning-box">
        <strong>Scaffold:</strong> This tool is scaffolded out with placeholder components. The actual prompt component content (HTML templates for each section) will be supplied and wired in later.
      </div>
    </>
  );
}
