import type { Metadata } from 'next';
import PageHeader from '../components/PageHeader';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for using the Fortrafied DLP testing platform.',
};

export default function TermsPage() {
  return (
    <>
      <PageHeader
        title="Terms of Service"
        description="Please read these terms carefully before using Fortrafied."
      />
      <main className="container section">
        <div className="legal-content">
          <p className="legal-updated">Last updated: April 6, 2025</p>

          <section className="legal-section">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using Fortrafied (&ldquo;the Site&rdquo;), you accept and agree
              to be bound by these Terms of Service. If you do not agree to these terms,
              please do not use the Site.
            </p>
          </section>

          <section className="legal-section">
            <h2>2. Description of Service</h2>
            <p>
              Fortrafied is a free, browser-based Data Loss Prevention (DLP) testing and
              validation platform. The Site provides tools for security professionals to
              test and evaluate their DLP solutions across multiple data protection vectors,
              including data in motion, data in use, and data at rest.
            </p>
            <p>
              All data processing occurs entirely within your browser. No user-submitted
              data is transmitted to, processed by, or stored on any server operated by
              Fortrafied.
            </p>
          </section>

          <section className="legal-section">
            <h2>3. Authorized Use Only</h2>
            <p>
              The tools and resources provided on this Site are intended exclusively for:
            </p>
            <ul>
              <li>Authorized security testing and validation of DLP solutions</li>
              <li>Educational purposes related to data loss prevention</li>
              <li>Evaluating and configuring data protection policies</li>
              <li>Security research conducted in compliance with applicable laws</li>
            </ul>
            <p>
              You agree to use this Site only for lawful purposes and in accordance with
              all applicable local, state, national, and international laws and regulations.
              You are solely responsible for ensuring that your use of this Site and its
              tools is authorized by your organization and complies with all relevant
              policies and laws.
            </p>
          </section>

          <section className="legal-section">
            <h2>4. Synthetic Data</h2>
            <p>
              All sample data generated by or provided through this Site is entirely
              synthetic and randomly generated. No real personal, financial, health, or
              otherwise sensitive information is included. Credit card numbers use valid
              format patterns but are not associated with real accounts. Social Security
              Numbers, names, addresses, and all other personally identifiable information
              are fabricated and do not correspond to real individuals.
            </p>
          </section>

          <section className="legal-section">
            <h2>5. No Data Collection</h2>
            <p>
              Fortrafied does not collect, store, transmit, or process any data you enter
              into the testing tools. All operations &mdash; including file parsing, regex
              matching, classification, and hashing &mdash; are performed locally in your
              browser using client-side JavaScript. No server-side processing of user content
              occurs.
            </p>
          </section>

          <section className="legal-section">
            <h2>6. Disclaimer of Warranties</h2>
            <p>
              The Site and all tools are provided &ldquo;as is&rdquo; and &ldquo;as
              available&rdquo; without any warranties of any kind, express or implied,
              including but not limited to warranties of merchantability, fitness for a
              particular purpose, accuracy, or non-infringement.
            </p>
            <p>
              Fortrafied does not warrant that:
            </p>
            <ul>
              <li>The Site will be uninterrupted, error-free, or secure</li>
              <li>The results obtained from testing tools will be accurate or reliable</li>
              <li>Any defects in the Site will be corrected</li>
              <li>The Site will meet your specific requirements or expectations</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>7. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, Fortrafied and its
              creator(s) shall not be liable for any indirect, incidental, special,
              consequential, or punitive damages, including but not limited to loss of
              data, revenue, profits, or business opportunities, arising out of or in
              connection with your use of the Site, even if advised of the possibility
              of such damages.
            </p>
          </section>

          <section className="legal-section">
            <h2>8. Third-Party Services</h2>
            <p>
              The Site is hosted on GitHub Pages and may reference third-party products,
              services, or trademarks. Fortrafied is an independent project and is not
              affiliated with, endorsed by, or sponsored by any company whose products
              or services may be referenced on the Site. All product names, logos, and
              brands are property of their respective owners.
            </p>
          </section>

          <section className="legal-section">
            <h2>9. Intellectual Property</h2>
            <p>
              The content, design, and code of Fortrafied are the intellectual property
              of its creator(s). The Site&apos;s source code is publicly available on GitHub.
              You may not reproduce, distribute, or create derivative works from the Site&apos;s
              content for commercial purposes without prior written permission.
            </p>
          </section>

          <section className="legal-section">
            <h2>10. Modifications to Terms</h2>
            <p>
              Fortrafied reserves the right to modify these Terms of Service at any time.
              Changes will be effective immediately upon posting to the Site. Your continued
              use of the Site following any changes constitutes acceptance of the revised
              terms.
            </p>
          </section>

          <section className="legal-section">
            <h2>11. Governing Law</h2>
            <p>
              These Terms of Service shall be governed by and construed in accordance with
              the laws of the United States, without regard to conflict of law principles.
            </p>
          </section>

          <section className="legal-section">
            <h2>12. Contact</h2>
            <p>
              If you have questions about these Terms of Service, please reach out via the
              contact information on the{' '}
              <a href="/about">About &amp; Contact</a> page.
            </p>
          </section>
        </div>
      </main>
    </>
  );
}
